---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Include Debian setup tasks
      ansible.builtin.include_tasks: debian-setup.yml
      when: ansible_os_family == 'Debian'

  roles:
    - role: shaneholloman.java
    - role: shaneholloman.jenkins

  post_tasks:
    - name: Check if Jenkins is running.
      ansible.builtin.uri:
        url: "http://127.0.0.1:8080/"
        status_code:
          - 200
          - 403
