---
- name: Converge
  hosts: all
  become: true

- name: Update apt cache.
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 600
  changed_when: false

- name: Set the java_packages variable.
  ansible.builtin.set_fact:
    java_packages:
      - openjdk-17-jdk
